name: DEV

on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'dev'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
          
      - name: Build and start services with Docker Compose
        run: |
          docker compose up -d

      - name: Check containers are running
        run: |
          docker ps

      - name: Wait for services to be ready
        run: |
          sleep 10
          docker compose ps
          
      - name: Run health check
        run: |
          curl -f http://localhost:8080/alive || exit 1
          curl -f http://localhost:8082/alive || exit 1
          curl -f http://localhost:8083/alive || exit 1
