name: CALLER

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        env-type: [dev, pre, pro]
    uses: saguit03/proyecto24-gb01/.github/workflows/learning-called.yml@actions
    with:
      env-type: ${{ matrix.env-type }}