name: PRO

on:
  workflow_run:
    workflows: [PRE]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: 'pro'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
          
      - name: Build and start services with Docker Compose
        run: |
          docker compose up -d

      - name: Check containers are running
        run: |
          docker ps

  on-failure:
    environment: 'pro'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      # - run: exit 1